version: '3.8'

services:
  populate_historical_data:
    image: trading-bot:latest
    command: python populate_historical_data.py
    environment:
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  populate_static_data:
    image: trading-bot:latest
    command: python populate_static_data.py
    environment:
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  trade_manager:
    image: trading-bot:latest
    command: python trade_manager.py
    environment:
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  trading_engine:
    image: trading-bot:latest
    command: python trading_engine.py
    environment:
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  telegram_controller:
    image: trading-bot:latest
    command: python telegram_controller.py
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"