version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"  # Flask-сервер
    volumes:
      - ./src:/app  # Для разработки
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - CHAT_ID=${CHAT_ID}